### ISSUE TITLE
Desktop App

### ISSUE THREAD

**Issue by ajsb85** [gradha/apptaster-to-html#3]
Can we work into a Polymer o Xul Based App?

**Comment by gradha** [comment]
No idea, I don't know any of these two things you mention.

**Comment by ajsb85** [comment]
Ok, try to write the XML Namespaces information of the apptaster file format, and I can build the desktop app with Polymer or XULRunner

https://www.polymer-project.org/0.5/
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/XULRunner

**Comment by ajsb85** [comment]
We can write the documentation on the Wiki
https://github.com/gradha/apptaster-to-html/wiki/AppTaster-File-Format

**Comment by gradha** [comment]
I'm not interested in reverse engineering the file format, maybe you should try to ask the apptaster author.

If you plan on going forward with this I can give you ownership of the repo since I would just get in the way.

**Comment by ajsb85** [comment]
Go ahead, Thank you

**Comment by ajsb85** [comment]
No me habia dado cuenta que hablas español. xD
